
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sholeh
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_out_tgl = new javax.swing.JLabel();
        txt_out_zodiak = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JTextField();
        txt_bln = new javax.swing.JTextField();
        btn_cek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nugraha Indra");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("41516120092");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tanggal Lahir (1..31) =");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Bulan (1..12) =");

        txt_out_tgl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_out_tgl.setText("Tanggal Lahir Anda =");

        txt_out_zodiak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_out_zodiak.setText("Zodiak Anda Adalah =");

        btn_cek.setText("Cek");
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_out_zodiak)
                    .addComponent(txt_out_tgl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cek))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cek))
                .addGap(39, 39, 39)
                .addComponent(txt_out_tgl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_out_zodiak)
                .addGap(0, 126, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(535, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        // TODO add your handling code here:
        String tgl, bul;
        int ntgl, nbul;
        
        tgl = txt_tgl.getText();
        bul = txt_bln.getText();
        
        if (checkUtil("Tanggal", tgl) && checkUtil("Bulan", bul))
        {
            ntgl = Integer.parseInt(tgl);
            nbul = Integer.parseInt(bul);
            
            if(ntgl > 31 || nbul > 12)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else if (nbul == 2 && ntgl > 29)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else if (nbul == 4 && ntgl > 30)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else if (nbul == 6 && ntgl > 30)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else if (nbul == 9 && ntgl > 30)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else if (nbul == 11 && ntgl > 30)
            {
                JOptionPane.showMessageDialog(this, "Anda salah input Tanggal dan Bulan");
                txt_out_tgl.setText("Tanggal Lahir Anda  = ");
                txt_out_zodiak.setText("Zodiak Anda Adalah = ");
            }
            else
            {
                String strBul = CekBulan(nbul);
                String strZoo = CekZodiak(ntgl, nbul);
                txt_out_tgl.setText("Tanggal Lahir Anda  = " + tgl + " " + strBul);
                txt_out_zodiak.setText("Zodiak Anda Adalah = " + strZoo);
            }
        }
    }//GEN-LAST:event_btn_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }
    
    private boolean isNumeric(String str)
    {
        return str != null && str.matches("[0-9.]+");
    }
    
    private boolean checkUtil(String name, String value)
    {
        boolean isOk = false;
        if (value.isEmpty())
        {
            JOptionPane.showMessageDialog(this, name + " wajib diisi");
        }
        else
        {
            if (isNumeric(value))
            {
                isOk = true;
            }
            else
            {
                JOptionPane.showMessageDialog(this, name + " Harus Diisi Angka");
            }
        }
        
        return isOk;
    }
    
    private String CekBulan(int tgl)
    {
        String bln;
        switch(tgl) {
            case 1:
                bln = "Januari";
                break;
            case 2:
                bln = "Februari";
                break;
            case 3:
                bln = "Maret";
                break;
            case 4:
                bln = "April";
                break;
            case 5:
                bln = "Mei";
                break;
            case 6:
                bln = "Juni";
                break;
            case 7:
                bln = "Juli";
                break;
            case 8:
                bln = "Agustus";
                break;
            case 9:
                bln = "September";
                break;
            case 10:
                bln = "Oktober";
                break;
            case 11:
                bln = "November";
                break;
            default: 
                bln = "Desember";
                break;
        }
        
        return bln;
    }
    
    private String CekZodiak(int tgl, int bln)
    {
        String out = null;
        if ((tgl >= 21 && bln == 3) || (tgl <= 19 && bln == 4))
        {
            out = "Aries";
        }
        else if ((tgl >= 20 && bln == 4) || (tgl <= 20 && bln == 5))
        {
            out = "Taurus";
        }
        else if ((tgl >= 21 && bln == 5) || (tgl <= 20 && bln == 6))
        {
            out = "Gemini";
        }
        else if ((tgl >= 21 && bln == 6) || (tgl <= 22 && bln == 7))
        {
            out = "Cancer";
        }
        else if ((tgl >= 23 && bln == 7) || (tgl <= 22 && bln == 8))
        {
            out = "Leo";
        }
        else if ((tgl >= 23 && bln == 8) || (tgl <= 22 && bln == 9))
        {
            out = "Virgo";
        }
        else if ((tgl >= 23 && bln == 9) || (tgl <= 22 && bln == 10))
        {
            out = "Libra";
        }
        else if ((tgl >= 23 && bln == 10) || (tgl <= 21 && bln == 11))
        {
            out = "Scorpio";
        }
        else if ((tgl >= 22 && bln == 11) || (tgl <= 21 && bln == 12))
        {
            out = "Sagitarius";
        }
        else if ((tgl >= 22 && bln == 12) || (tgl <= 19 && bln == 1))
        {
            out = "Capricorn";
        }
        else if ((tgl >= 20 && bln == 1) || (tgl <= 18 && bln == 2))
        {
            out = "Aquarius";
        }
        else if ((tgl >= 19 && bln == 2) || (tgl <= 20 && bln == 3))
        {
            out = "Pisces";
        }
        return out;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_bln;
    private javax.swing.JLabel txt_out_tgl;
    private javax.swing.JLabel txt_out_zodiak;
    private javax.swing.JTextField txt_tgl;
    // End of variables declaration//GEN-END:variables
}
